# Usa la imagen oficial de Tomcat
FROM tomcat:9.0-jdk11

# Copia tu archivo WAR al directorio webapps de Tomcat
COPY proyectoED2-1.0.war target/usr/local/tomcat/webapps/

# Expone el puerto 8080 (puerto predeterminado de Tomcat)
EXPOSE 8080

# Comando para iniciar Tomcat
CMD ["catalina.sh", "run"]
